version: '3.7'

services:
  dns:
    image: strm/dnsmasq
    hostname: dns0
    entrypoint:
      - dnsmasq
      - "-d"
    volumes:
      - ./etc/dnsmasq.conf:/etc/dnsmasq.conf
      - ./hosts.d:/etc/dnsmasq/hosts.d
    networks:
      net0:
        ipv4_address: 10.42.10.254
  host1:
    image: simple-server
    hostname: host1.safari
    volumes:
      - ./etc/resolv.conf:/etc/resolv.conf
    ports:
      - 8101:80
    dns:
      - 10.42.10.254
    networks:
      net0:
        ipv4_address: 10.42.10.101

  host2:
    image: simple-server
    hostname: host2.safari
    volumes:
      - ./etc/resolv.conf:/etc/resolv.conf
    ports:
      - 8102:80
    dns:
      - 10.42.10.254
    networks:
      net0:
        ipv4_address: 10.42.10.102

  host3:
    image: simple-server 
    hostname: host3.safari
    volumes:
      - ./etc/resolv.conf:/etc/resolv.conf
    ports:
      - 8103:80
    dns:
      - 10.42.10.254
    networks:
      net0:
        ipv4_address: 10.42.10.103

networks:
 net0:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: 10.42.10.0/24

